---
- name: change hostname
  hosts: eSensesPi
  vars_files:
  - variables.yaml
  tasks:
  - name: Update hostname
    shell: hn=$(/bin/hostname) && echo {{ hostname }} > /etc/hostname && /bin/sed -i -- "s/$hn/{{ hostname }}/g" /etc/hosts
    become: True
    become_method: sudo
  - name: Restart {{ hostname }}
    shell: reboot
    become: True
    become_method: sudo
    async: 1
    poll: 0
    ignore_errors: true
  - name: Wait for {{ ansible_ssh_host }} to restart
    local_action: wait_for host="{{ ansible_ssh_host }}" delay=10 connect_timeout=5 state=started timeout=30
