---
- name: test1
  hosts: eSensesPi
  vars_files:
  - variables.yaml
  tasks:
  - name: Create service for reader
    template:
      src: templates/reader.service.j2
      dest: /etc/systemd/system/reader.service
      mode: 644
    become: True
    become_method: sudo
  - name: Tell systemd to run the service
    systemd:
      state: started
      daemon-reload: yes
      name: reader
    become: True
    become_method: sudo
